import ejs from 'ejs';
import path from 'path';
import fs from 'fs/promises';
import { AnalysisResult } from './aiAnalyzer.js';
import { logger } from '../core/logger.js';
import { DateTime } from 'luxon';

/**
 * ===================================
 * 报表渲染服务 (Node.js/EJS 版)
 * ===================================
 */

export class ReportRenderer {
  /**
   * 获取信号等级和 Emoji
   */
  private getSignalLevel(result: AnalysisResult) {
    const advice = result.operation_advice;
    const score = result.sentiment_score;

    if (advice.includes('强烈买入')) return { text: '强烈买入', emoji: '💚' };
    if (advice.includes('买入') || advice.includes('加仓')) return { text: '买入', emoji: '🟢' };
    if (advice.includes('持有')) return { text: '持有', emoji: '🟡' };
    if (advice.includes('观望')) return { text: '观望', emoji: '⚪' };
    if (advice.includes('减仓')) return { text: '减仓', emoji: '🟠' };
    if (advice.includes('卖出')) return { text: '卖出', emoji: '🔴' };

    // 兜底基于分数
    if (score >= 80) return { text: '强烈买入', emoji: '💚' };
    if (score >= 65) return { text: '买入', emoji: '🟢' };
    if (score >= 55) return { text: '持有', emoji: '🟡' };
    if (score >= 45) return { text: '观望', emoji: '⚪' };
    return { text: '卖出', emoji: '🔴' };
  }

  /**
   * 渲染报告
   */
  async render(results: AnalysisResult[], type: 'markdown' | 'brief' = 'markdown'): Promise<string> {
    const reportDate = DateTime.now().toFormat('yyyy-MM-dd');
    const timestamp = DateTime.now().toFormat('yyyy-MM-dd HH:mm:ss');

    const sortedResults = [...results].sort((a, b) => b.sentiment_score - a.sentiment_score);
    const enriched = sortedResults.map(r => ({
      result: r,
      ...this.getSignalLevel(r)
    }));

    const buyCount = results.filter(r => r.decision_type === 'buy').length;
    const sellCount = results.filter(r => r.decision_type === 'sell').length;

    // 这里使用简单的字符串模板替代 EJS 文件读取，以防模板文件缺失
    // 实际生产中可以读取 template/ 目录下的 .ejs 文件
    let template = `
# 🎯 <%- reportDate %> 美股智能分析报告

> 运行时间: <%- timestamp %>
> 统计: <%- buyCount %> 买入 | <%- sellCount %> 卖出 | 共 <%- results.length %> 只

---

<% enriched.forEach(function(item){ %>
### <%- item.emoji %> <%- item.result.name %> (<%- item.result.code %>)
- **建议**: <%- item.result.operation_advice %> (评分: <%- item.result.sentiment_score %>)
- **结论**: <%- item.result.analysis_summary %>
<% if (item.result.buy_reason) { %>- **理由**: <%- item.result.buy_reason %><% } %>

---
<% }); %>

*Generated by Gemini 3.0 CLI*
`;

    try {
      return ejs.render(template, {
        reportDate,
        timestamp,
        results,
        enriched,
        buyCount,
        sellCount
      });
    } catch (e) {
      logger.error(`[Renderer] 渲染失败: ${e}`);
      return "报告生成失败";
    }
  }
}

export const reportRenderer = new ReportRenderer();
